[opener]
play = [
  { run = 'mpv %s', orphan = true, for = "unix" },
]
view-image-mpv = [
  { run = 'mpv %s', orphan = true, for = "unix" },
]
play-audio-mpv = [
  { run = 'mpv --vid=no %s', orphan = true, for = "unix" },
]

[[open.prepend_rules]]
mime = "video/*"
use = [ "play", "reveal" ] # "play" refers to the 'play' opener defined above

[[open.prepend_rules]]
mime = "image/*"
use = [ "view-image-mpv", "reveal" ] # "view-image-mpv" refers to the custom opener

[[open.prepend_rules]]
mime = "audio/*"
use = [ "play-audio-mpv", "reveal" ]

